// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSU17Ft0OFTbaAjGvJKHIpvGTlegVLdk',
    appId: '1:974420597974:web:f5acf3d8c4255d696ebd77',
    messagingSenderId: '974420597974',
    projectId: 'motogenie-66388',
    authDomain: 'motogenie-66388.firebaseapp.com',
    storageBucket: 'motogenie-66388.firebasestorage.app',
    measurementId: 'G-PMH3H3EKZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkRFHFaMqEZQg3BhDR-nP0dfbg1ZRGvM8',
    appId: '1:974420597974:android:0787965134afb5ab6ebd77',
    messagingSenderId: '974420597974',
    projectId: 'motogenie-66388',
    storageBucket: 'motogenie-66388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALRUbVcXLKmyTIyMy55FlXZ4GhPb3_a9c',
    appId: '1:974420597974:ios:b295a050a4c3e08a6ebd77',
    messagingSenderId: '974420597974',
    projectId: 'motogenie-66388',
    storageBucket: 'motogenie-66388.firebasestorage.app',
    iosBundleId: 'com.example.motogenieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALRUbVcXLKmyTIyMy55FlXZ4GhPb3_a9c',
    appId: '1:974420597974:ios:b295a050a4c3e08a6ebd77',
    messagingSenderId: '974420597974',
    projectId: 'motogenie-66388',
    storageBucket: 'motogenie-66388.firebasestorage.app',
    iosBundleId: 'com.example.motogenieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFSU17Ft0OFTbaAjGvJKHIpvGTlegVLdk',
    appId: '1:974420597974:web:79bad1d4af80998e6ebd77',
    messagingSenderId: '974420597974',
    projectId: 'motogenie-66388',
    authDomain: 'motogenie-66388.firebaseapp.com',
    storageBucket: 'motogenie-66388.firebasestorage.app',
    measurementId: 'G-83EDMRSJS8',
  );

}